name: Update formulas

on:
  # on demand
  workflow_dispatch:
  # on schedule
  schedule:
    # Every monday at 6am
    - cron: '0 6 * * 1'

jobs:
  update:
    strategy:
      matrix:
          formula:
            - name: stsmfa-cli
              description: A small CLI to help with creating AWS profile for MFA protected sessions.
              test: 'assert_match "Usage:", shell_output("#{bin}/stsmfa --help")'
    permissions:
      contents: write # for peter-evans/create-pull-request to create branch
      pull-requests: write # for peter-evans/create-pull-request to create a PR
    runs-on: ubuntu-latest
    name: Update ${{ matrix.formula.name }}
    steps:
      - uses: actions/checkout@v7
      - uses: Homebrew/actions/setup-homebrew@master
      - run: |
          PYTHON_PACKAGE_SOURCE_URL=$(curl --silent --show-error "https://pypi.org/pypi/${{ matrix.formula.name }}/json" \
          | jq -r '.urls[] | select(.packagetype == "sdist") | .url')
          test -n "${PYTHON_PACKAGE_SOURCE_URL}"
          touch /tmp/generated-formula-marker
          brew create --python --set-name "${{ matrix.formula.name }}" "${PYTHON_PACKAGE_SOURCE_URL}"
          GENERATED_FORMULA_PATH=$(find . -maxdepth 1 -name '*.rb' -newer /tmp/generated-formula-marker -print -quit)
          test -n "${GENERATED_FORMULA_PATH}"
          sed 's@Shiny new formula@${{ matrix.formula.description }}@g' "${GENERATED_FORMULA_PATH}" \
          | sed 's@    false@    ${{ matrix.formula.test }}@g' \
          > Formula/${{ matrix.formula.name }}.rb
          rm -f /tmp/generated-formula-marker "${GENERATED_FORMULA_PATH}"
      - run: cat Formula/${{ matrix.formula.name }}.rb
      - uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/formula/${{ matrix.formula.name }}
          title: Update formula ${{ matrix.formula.name }}
          commit-message: Update formula ${{ matrix.formula.name }}
